name: testing

on:
  push:
    branches:
      - '*'

permissions:
  actions: write
  checks: write
  contents: write
  pull-requests: write

jobs:
  test:
    name: Test
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4

    - name: Show env
      run: env

    - name: Show current version of Xcode
      run: xcodebuild -version

    - name: Run build
      run: xcodebuild -sdk iphonesimulator -workspace ${PWD}/SPIClient-iOS.xcworkspace -scheme SPIClient-iOS clean build CODE_SIGNING_ALLOWED=NO
